selenium-hub:
  image: selenium/hub
  container_name: 'selenium-hub'
  ports:
    - 4444:4444

chrome:
  image: selenium/node-chrome-debug
  environment:
    HUB_PORT_4444_TCP_ADDR: selenium-hub
    HUB_PORT_4444_TCP_PORT: 4444
    DBUS_SESSION_BUS_ADDRESS: /dev/null
  ports:
    - 9001:5900
  container_name: 'chrome'
  links:
    - selenium-hub:hub
  volumes:
    - /dev/shm:/dev/shm
    - ./data:/data

lab:
  image: jupyter/base-notebook
  volumes:
    - ./notebooks/:/notebooks
    - ./data/:/notebooks/data
  ports:
    - "8888:8888"
  container_name: 'lab'
  environment:
    - JUPYTER_ENABLE_LAB=1
  command: start-notebook.sh --NotebookApp.notebook_dir=/notebooks --NotebookApp.token='' --NotebookApp.password=''
  links:
    - selenium-hub:hub
